// Generated by https://quicktype.io
import { FormikActions } from "formik";

export interface ArticleResponseDto {
  articles: Article[];
  articlesCount: number;
}

export interface Article {
  title: string;
  slug: string;
  body: string;
  createdAt: string;
  updatedAt: string;
  tagList: string[];
  description: string;
  author: Author;
  favorited: boolean;
  favoritesCount: number;
}

export interface Author {
  username: string;
  bio: null | string;
  image: string;
  following: boolean;
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Tags {
  tags: string[];
}

export interface User {
  id: number;
  email: string;
  createdAt: string;
  updatedAt: string;
  username: string;
  bio: string;
  image: string;
  token: string;
}

export interface SettingsValues {
  image: string;
  username: string;
  bio: string;
  email: string;
  newPassword: string;
}

export interface LoginResponse {
  user: User;
}

export interface LoginValues {
  email: string;
  password: string;
}

export interface LoginUserPayload {
  email: string;
  password: string;
}

export interface UserSettings {
  image: string;
  username: string;
  bio: string;
  email: string;
  password: string;
  handleFieldError: FormikActions<SettingsValues>;
}

export interface SaveSettingsResponse {
  user: User;
}
