// Generated by https://quicktype.io

export interface ArticleResponseDto {
  articles: Article[];
  articlesCount: number;
}

export interface Article {
  title: string;
  slug: string;
  body: string;
  createdAt: string;
  updatedAt: string;
  tagList: string[];
  description: string;
  author: Author;
  favorited: boolean;
  favoritesCount: number;
}

export interface Author {
  username: string;
  bio: null | string;
  image: string;
  following: boolean;
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface Tags {
  tags: string[];
}
